# (c) 2016 DataNexus Inc.  All Rights Reserved
---
# If a repo_name was passed in by the user then reconfigure the {{repository_name}}.repo
# file so that the baseurl lines all point to the local mirror's URL (instead of the default
# server for that repository) and comment out the mirrorlist lines in that same file
- set_fact:
    repo_name: "{{repository_name | default('CentOS-Base')}}"
    default_baseurl_regex: "^#?(baseurl=)(http://[^\\/]+\\/.*)(/\\$releasever/.*)$"
    default_baseurl_relpx: "\\g<1>{{yum_repository}}\\g<3>"
    default_mirrorlist_regex: "^(mirrorlist=http://mirrorlist.centos.org/.*)$"
    default_mirrorlist_replx: "#\\g<1>"
- block:
  # Backup the default repository files (if we haven't already) and then point them
  # at the new repositories
  - name: Backup default {{repo_name | default('CentOS-Base')}}.repo file
    copy:
      src: "/etc/yum.repos.d/{{repo_name}}.repo"
      dest: "/etc/yum.repos.d/.{{repo_name}}.repo.bak"
      remote_src: true
      mode: 0644
      force: no
  - name: Backup default {{repo_name | default('CentOS-Base')}}-testing.repo file (if exists)
    copy:
      src: "/etc/yum.repos.d/{{repo_name}}-testing.repo"
      dest: "/etc/yum.repos.d/.{{repo_name}}-testing.repo.bak"
      remote_src: true
      mode: 0644
      force: no
    failed_when: false
  - name: And remove {{repo_name | default('CentOS-Base')}}-testing.repo file (if exists)
    file:
      path: "/etc/yum.repos.d/{{repo_name}}-testing.repo"
      state: absent
    failed_when: false
  - name: Point repositories in {{repo_name | default('CentOS-Base')}}.repo file to mirror
    replace:
      dest: "/etc/yum.repos.d/{{repo_name | default('CentOS-Base')}}.repo"
      regexp: "{{((regex_repl_vals | default([])).baseurl | default([])).regex | default(default_baseurl_regex)}}"
      replace: "{{((regex_repl_vals | default([])).baseurl | default([])).replx | default(default_baseurl_relpx)}}"
  - name: Comment out mirrorlist entries
    replace:
      dest: "/etc/yum.repos.d/{{repo_name | default('CentOS-Base')}}.repo"
      regexp: "{{((regex_repl_vals | default([])).mirrorlist | default([])).regex | default(default_mirrorlist_regex)}}"
      replace: "{{((regex_repl_vals | default([])).mirrorlist | default([])).replx | default(default_mirrorlist_replx)}}"
  become: true
  when: not(yum_repository is undefined or yum_repository is none or yum_repository | trim == '')
# if a repo_name was not passed in, then we copy the original files back from the backup copies
# we created earlier
- block:
   # restore the default repository files
  - name: Restore the default {{repo_name | default('CentOS-Base')}}.repo file from the backup copy
    copy:
      src: "/etc/yum.repos.d/.{{repo_name}}.repo.bak"
      dest: "/etc/yum.repos.d/{{repo_name}}.repo"
      remote_src: true
      force: true
      mode: 0644
  - name: Restore the default {{repo_name | default('CentOS-Base')}}-testing.repo file from the backup copy
    become: true
    copy:
      src: "/etc/yum.repos.d/.{{repo_name}}.repo.bak"
      dest: "/etc/yum.repos.d/{{repo_name}}.repo"
      remote_src: true
      mode: 0644
      force: true
    ignore_errors: yes
  become: true
  when: yum_repository is undefined or yum_repository is none or yum_repository | trim == ''
# Finally, ensure that we clean up the yum cache and reload the (potentially new)
# list of yum repositories
- name: "remove all repository entries from the current yum cache"
  become: true
  command: yum clean all
  args:
    warn: no
- name: "list all configured yum repositories"
  become: true
  command: yum repolist all
  args:
    warn: no
