---
- set_fact: http_proxy='{{proxy_env.http_proxy}}'
  when: proxy_env is defined
- set_fact: no_proxy='{{proxy_env.no_proxy}}'
  when: proxy_env is defined
- name: Initialize environment_vars
  set_fact: environment_vars={}
- name: Set no_proxy environment variables
  set_fact:
    no_proxy_vars:
      no_proxy: "{{ no_proxy }}"
      NO_PROXY: "{{ no_proxy }}"
  when: not (no_proxy is undefined or no_proxy is none or no_proxy | trim == '')
- name: Set proxy environment variables
  set_fact:
    proxy_vars:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ http_proxy }}"
      HTTP_PROXY: "{{ http_proxy }}"
      HTTPS_PROXY: "{{ http_proxy }}"
  when: not (http_proxy is undefined or http_proxy is none or http_proxy | trim == '')
- name: Set environment variables
  set_fact:
    environment_vars:  "{{ no_proxy_vars|default({}) | combine(proxy_vars|default({})) }}"
- name: Unpack IAG certificates
  unarchive:
    src: "{{proxy_certs_file}}"
    dest: /etc/pki/ca-trust/source/anchors
  when: not (http_proxy is undefined or http_proxy is none or http_proxy | trim == '')
- name: Add certificates to list of trusted certs
  shell: update-ca-trust
  when: not (http_proxy is undefined or http_proxy is none or http_proxy | trim == '')
