# (c) 2017 DataNexus Inc.  All Rights Reserved. 
---
- name: "Installing {{ package_list }}"
  become: true
  package:
    name: "{{ (package_list | default([])) | join(',') }}"
    state: present
  environment: "{{ proxy_env | default({}) }}"
  when: not (package_list is undefined or package_list is none or package_list == [])
