# (c) 2017 DataNexus Inc.  All Rights Reserved. 
---
- name: "Installing {{ package_list }}"
  become: true
  package:
    name: "{{ (package_list | default([])) | join(',') }}"
    state: present
  environment: "{{ proxy_env | default({}) }}"
